// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1RainerStropek.DataAccess;

#nullable disable

namespace WebApplication1RainerStropek.Migrations
{
    [DbContext(typeof(VideoGameDataContext))]
    partial class VideoGameDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1RainerStropek.DataAccess.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("GameGenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("personalRating")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GameGenreId");

                    b.ToTable("games");
                });

            modelBuilder.Entity("WebApplication1RainerStropek.DataAccess.GameGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("gameGenres");
                });

            modelBuilder.Entity("WebApplication1RainerStropek.DataAccess.Game", b =>
                {
                    b.HasOne("WebApplication1RainerStropek.DataAccess.GameGenre", "Genre")
                        .WithMany("games")
                        .HasForeignKey("GameGenreId");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("WebApplication1RainerStropek.DataAccess.GameGenre", b =>
                {
                    b.Navigation("games");
                });
#pragma warning restore 612, 618
        }
    }
}
